services:
  db:
    image: postgres:17.4-bookworm
    env_file:
      - .local.env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: next
      # POSTGRES_PASSWORD_FILE:
    ports:
      - 5432:5432
    # volumes:
      # - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 6002:8080
